{% set name = "playground" %}
{% set version = "0.0.3" %}
# The recent jax version required by this package require at least python 3.10
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/playground-{{ version }}.tar.gz
  sha256: 31b0f6e4090fb14b13221bfbf476a652fe9b17cbd0b3ce92a6e2babcb88a3e3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - etils
    - flax
    - jax
    - lxml
    - ml-collections
    - mujoco-mjx >=3.2.7
    - mujoco-python >=3.2.7
    - tqdm
    - brax >=0.12.1

test:
  imports:
    - mujoco_playground
  commands:
    - pip check
    - pytest --pyargs mujoco_playground
  requires:
    - pip
    - pytest
    - python {{ python_min }}
    - absl-py
    - dm-control
    - git

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://playground.mujoco.org/
  summary: "An open-source library for GPU-accelerated robot learning and sim-to-real transfer."

extra:
  recipe-maintainers:
    - traversaro
